# Generated by Django 5.2.4 on 2025-07-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_cantidad_producto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=10, help_text='Punto de reorden para el producto'),
        ),
    ]
